### ISSUE TITLE
create_cookie() got unexpected keyword arguments: ['sameSite'] during cli execution

### ISSUE THREAD

**Issue by ksetdekov** [costastf/mapscookiegettercli#14]
Installed the tool and ran it under Win 10 and Python 3.7
running the CLI tool with a `maps-cookie-getter` command results in the following output:

`
2020-04-11 19:08:37 DESKTOP-5EDO4R2 chrome.bootstrapper[17456] INFO Deleting all cookies
2020-04-11 19:08:37 DESKTOP-5EDO4R2 chrome.bootstrapper[17456] INFO Returning driver
2020-04-11 19:08:37 DESKTOP-5EDO4R2 cookiegetter.CookieGetter[17456] INFO Starting interactive login process.
2020-04-11 19:09:06 DESKTOP-5EDO4R2 cookiegetter.CookieGetter[17456] INFO Log in successful, getting session cookies.
2020-04-11 19:09:06 DESKTOP-5EDO4R2 cookiegetter.CookieGetter[17456] INFO Transferring cookies to a requests session.
Traceback (most recent call last):
  File "C:\Users\ksetd\PycharmProjects\ML_light_switch\venv\Scripts\maps-cookie-getter-script.py", line 11, in <module>
    load_entry_point('mapscookiegettercli==0.2.0', 'console_scripts', 'maps-cookie-getter')()
  File "C:\Users\ksetd\PycharmProjects\ML_light_switch\venv\lib\site-packages\mapscookiegettercli\mapscookiegettercli.py", line 92, in main
    getter.run()
  File "C:\Users\ksetd\PycharmProjects\ML_light_switch\venv\lib\site-packages\mapscookiegettercli\library\cookiegetter.py", line 179, in run
    session = self._get_session(driver)
  File "C:\Users\ksetd\PycharmProjects\ML_light_switch\venv\lib\site-packages\mapscookiegettercli\library\cookiegetter.py", line 197, in _get_session
    session.cookies.set(**cookie)
  File "C:\Users\ksetd\PycharmProjects\ML_light_switch\venv\lib\site-packages\requests\cookies.py", line 214, in set
    c = create_cookie(name, value, **kwargs)
  File "C:\Users\ksetd\PycharmProjects\ML_light_switch\venv\lib\site-packages\requests\cookies.py", line 466, in create_cookie
    raise TypeError(err % list(badargs))
TypeError: create_cookie() got unexpected keyword arguments: ['sameSite']
`
Is theres something that  i can do to help fix the mapscookiegettercli utility?

**Comment by costastf** [comment]
Hi, this is a deprecated tool. Locationsharinglib is refactored to accept text based cookies exported from a browser add-on so this tool is no longer needed and thus no longer updated. It is still on line only for reference because it has some nice browser identification features.

**Comment by costastf** [comment]
If you want to fix a local copy for yourself I think that adding "sameSite" to the list of values in line 192 of cookiegettet.py under the library directory would fix it for you. I will close this issue and next week I will update the documentation to clearly state that this is deprecated.
