### ISSUE TITLE
Run on Rpi

### ISSUE THREAD

**Issue by fatuuse** [costastf/mapscookiegettercli#6]
Is it possible to run it on Rpi. I only manage to install Chromium.

**Comment by costastf** [comment]
It should run just fine on rpi, but chromium is not a supported browser. Install firefox and give it a try.

**Comment by crimean7** [comment]
Can't get to work mapscookiegettercli with a response:
2019-08-02 16:36:59 hassio cookiegetter.CookieGetter[4256] INFO Identified OS as linux
Traceback (most recent call last):
File "/srv/homeassistant/bin/maps-cookie-getter", line 10, in
sys.exit(main())
File "/srv/homeassistant/lib/python3.7/site-packages/mapscookiegettercli/mapscookiegettercli.py", line 91, in main
getter = CookieGetter()
File "/srv/homeassistant/lib/python3.7/site-packages/mapscookiegettercli/library/cookiegetter.py", line 81, in init
self.default_browser = self._identify_default_browser(self.os)
File "/srv/homeassistant/lib/python3.7/site-packages/mapscookiegettercli/library/cookiegetter.py", line 101, in _identify_default_browser
raise UnsupportedDefaultBrowser
mapscookiegettercli.mapscookiegettercliexceptions.UnsupportedDefaultBrowser

And, I have Firefox installed as the Chromium isn't supported.

Home you can direct me to a method to solve the issue.

Thanks

**Comment by costastf** [comment]
Have you set firefox as default though?

**Comment by crimean7** [comment]
Thanks for quick response.
And in GUI and with sudo update-alternatives --config x-www-browser

**Comment by crimean7** [comment]
I'm trying to do it in virtual environment

**Comment by costastf** [comment]
What does

xdg-settings get default-web-browser

return?

**Comment by crimean7** [comment]
firefox-esr.desktop

**Comment by costastf** [comment]
Thats why it fails, it expects "firefox". I suggest you locate that file
and make a link to just firefox or something like that.

**Comment by crimean7** [comment]
Will give a try. Thanks
